GET https://jsonplaceholder.typicode.com/users
###
GET https://em123ud827.execute-api.us-east-1.amazonaws.com/customers
###

POST https://em123ud827.execute-api.us-east-1.amazonaws.com/customers
content-type: application/json

{
    "name": "superman",
    "age": 85412584
}
